server:
  port: 8080

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/wsp_db}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: '#NPCuong0208'
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1077126250239-b287em2akuamdkkdpgdq8uicq849hpcs.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  mail:
    host: smtp.gmail.com
    port: 587
    username: phucuong479@gmail.com # Thay bằng email của bạn
    password: sols oqyo ypjv gmru # Thay bằng App Password của Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

otp:
  expiration: 300

